### ISSUE TITLE
environment problem "Torch not compiled with CUDA enabled"

### ISSUE THREAD

**Issue by silencht** [ALRhub/d3il#2]
Thanks your awesome work !  I have a problem running my code, and shell log below:
```bash
(base) silencht@silencht:~/d3il$ bash install.sh 
New Environment Name:
d3il2
Creating new conda environment d3il2
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/silencht/anaconda3/envs/d3il2

  added / updated specs:
    - python=3.10.8


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge 
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu 
  bzip2              conda-forge/linux-64::bzip2-1.0.8-hd590300_5 
  ca-certificates    conda-forge/linux-64::ca-certificates-2024.2.2-hbcca054_0 
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.40-h55db66e_0 
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5 
  libgcc-ng          conda-forge/linux-64::libgcc-ng-13.2.0-h77fa898_7 
  libgomp            conda-forge/linux-64::libgomp-13.2.0-h77fa898_7 
  libnsl             conda-forge/linux-64::libnsl-2.0.1-hd590300_0 
  libsqlite          conda-forge/linux-64::libsqlite-3.45.3-h2797004_0 
  libuuid            conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0 
  libzlib            conda-forge/linux-64::libzlib-1.2.13-hd590300_5 
  ncurses            conda-forge/linux-64::ncurses-6.5-h59595ed_0 
  openssl            conda-forge/linux-64::openssl-3.3.0-hd590300_0 
  pip                conda-forge/noarch::pip-24.0-pyhd8ed1ab_0 
  python             conda-forge/linux-64::python-3.10.8-h4a9ceb5_0_cpython 
  readline           conda-forge/linux-64::readline-8.2-h8228510_1 
  setuptools         conda-forge/noarch::setuptools-69.5.1-pyhd8ed1ab_0 
  tk                 conda-forge/linux-64::tk-8.6.13-noxft_h4845f30_101 
  tzdata             conda-forge/noarch::tzdata-2024a-h0c530f3_0 
  wheel              conda-forge/noarch::wheel-0.43.0-pyhd8ed1ab_1 
  xz                 conda-forge/linux-64::xz-5.2.6-h166bdaf_0 


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

Activating d3il2
Warning: 'conda-forge' already in 'channels' list, moving to the top
Install mamba
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/silencht/anaconda3/envs/d3il2

  added / updated specs:
    - mamba


The following NEW packages will be INSTALLED:

  archspec           conda-forge/noarch::archspec-0.2.3-pyhd8ed1ab_0 
  boltons            conda-forge/noarch::boltons-24.0.0-pyhd8ed1ab_0 
  brotli-python      conda-forge/linux-64::brotli-python-1.1.0-py310hc6cd4ac_1 
  c-ares             conda-forge/linux-64::c-ares-1.28.1-hd590300_0 
  certifi            conda-forge/noarch::certifi-2024.2.2-pyhd8ed1ab_0 
  cffi               conda-forge/linux-64::cffi-1.16.0-py310h2fee648_0 
  charset-normalizer conda-forge/noarch::charset-normalizer-3.3.2-pyhd8ed1ab_0 
  colorama           conda-forge/noarch::colorama-0.4.6-pyhd8ed1ab_0 
  conda              conda-forge/linux-64::conda-24.4.0-py310hff52083_0 
  conda-libmamba-so~ conda-forge/noarch::conda-libmamba-solver-24.1.0-pyhd8ed1ab_0 
  conda-package-han~ conda-forge/noarch::conda-package-handling-2.2.0-pyh38be061_0 
  conda-package-str~ conda-forge/noarch::conda-package-streaming-0.9.0-pyhd8ed1ab_0 
  distro             conda-forge/noarch::distro-1.9.0-pyhd8ed1ab_0 
  fmt                conda-forge/linux-64::fmt-10.2.1-h00ab1b0_0 
  icu                conda-forge/linux-64::icu-73.2-h59595ed_0 
  idna               conda-forge/noarch::idna-3.7-pyhd8ed1ab_0 
  jsonpatch          conda-forge/noarch::jsonpatch-1.33-pyhd8ed1ab_0 
  jsonpointer        conda-forge/linux-64::jsonpointer-2.4-py310hff52083_3 
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0 
  krb5               conda-forge/linux-64::krb5-1.21.2-h659d440_0 
  libarchive         conda-forge/linux-64::libarchive-3.7.2-h2aa1ff5_1 
  libcurl            conda-forge/linux-64::libcurl-8.7.1-hca28451_0 
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2 
  libev              conda-forge/linux-64::libev-4.33-hd590300_2 
  libiconv           conda-forge/linux-64::libiconv-1.17-hd590300_2 
  libmamba           conda-forge/linux-64::libmamba-1.5.8-had39da4_0 
  libmambapy         conda-forge/linux-64::libmambapy-1.5.8-py310h39ff949_0 
  libnghttp2         conda-forge/linux-64::libnghttp2-1.58.0-h47da74e_1 
  libsolv            conda-forge/linux-64::libsolv-0.7.29-ha6fb4c9_0 
  libssh2            conda-forge/linux-64::libssh2-1.11.0-h0841786_0 
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-13.2.0-hc0a3c3a_7 
  libxml2            conda-forge/linux-64::libxml2-2.12.6-h232c23b_2 
  lz4-c              conda-forge/linux-64::lz4-c-1.9.4-hcb278e6_0 
  lzo                conda-forge/linux-64::lzo-2.10-hd590300_1001 
  mamba              conda-forge/linux-64::mamba-1.5.8-py310h51d5547_0 
  menuinst           conda-forge/linux-64::menuinst-2.0.2-py310hff52083_0 
  packaging          conda-forge/noarch::packaging-24.0-pyhd8ed1ab_0 
  platformdirs       conda-forge/noarch::platformdirs-4.2.1-pyhd8ed1ab_0 
  pluggy             conda-forge/noarch::pluggy-1.5.0-pyhd8ed1ab_0 
  pybind11-abi       conda-forge/noarch::pybind11-abi-4-hd8ed1ab_3 
  pycosat            conda-forge/linux-64::pycosat-0.6.6-py310h2372a71_0 
  pycparser          conda-forge/noarch::pycparser-2.22-pyhd8ed1ab_0 
  pysocks            conda-forge/noarch::pysocks-1.7.1-pyha2e5f31_6 
  python_abi         conda-forge/linux-64::python_abi-3.10-4_cp310 
  reproc             conda-forge/linux-64::reproc-14.2.4.post0-hd590300_1 
  reproc-cpp         conda-forge/linux-64::reproc-cpp-14.2.4.post0-h59595ed_1 
  requests           conda-forge/noarch::requests-2.31.0-pyhd8ed1ab_0 
  ruamel.yaml        conda-forge/linux-64::ruamel.yaml-0.18.6-py310h2372a71_0 
  ruamel.yaml.clib   conda-forge/linux-64::ruamel.yaml.clib-0.2.8-py310h2372a71_0 
  tqdm               conda-forge/noarch::tqdm-4.66.4-pyhd8ed1ab_0 
  truststore         conda-forge/noarch::truststore-0.8.0-pyhd8ed1ab_0 
  urllib3            conda-forge/noarch::urllib3-2.2.1-pyhd8ed1ab_0 
  yaml-cpp           conda-forge/linux-64::yaml-cpp-0.8.0-h59595ed_0 
  zstandard          conda-forge/linux-64::zstandard-0.19.0-py310h5764c6d_0 
  zstd               conda-forge/linux-64::zstd-1.5.6-ha6fb4c9_0 


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Installing dependencies...

Looking for: ['pytorch==1.13.0', 'torchvision==0.14.0']

pkgs/main/linux-64 (check zst)                      Checked  2.2s
pkgs/main/noarch (check zst)                        Checked  0.1s
pkgs/r/linux-64 (check zst)                         Checked  0.1s
pkgs/r/noarch (check zst)                           Checked  0.1s
pkgs/main/linux-64                                   6.0MB @  16.9MB/s  1.8s
pkgs/main/noarch                                   711.8kB @ 399.4kB/s  1.9s
pkgs/r/linux-64                                      1.6MB @ 865.7kB/s  2.0s
pkgs/r/noarch                                        2.1MB @   1.0MB/s  1.9s
conda-forge/noarch                                  14.6MB @   2.2MB/s  7.8s
conda-forge/linux-64                                34.2MB @   4.0MB/s 10.9s

Pinned packages:
  - python 3.10.*


Transaction

  Prefix: /home/silencht/anaconda3/envs/d3il2

  Updating specs:

   - pytorch==1.13.0
   - torchvision==0.14.0
   - ca-certificates
   - certifi
   - openssl


  Package                Version  Build                     Channel          Size
───────────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────────

  + cudatoolkit           11.8.0  h4ba93d1_13               conda-forge     716MB
  + jpeg                      9e  h0b41bf4_3                conda-forge     240kB
  + libpng                1.6.43  h2797004_0                conda-forge     288kB
  + ninja                 1.12.0  h00ab1b0_0                conda-forge       2MB
  + libprotobuf          3.21.12  hfc55251_2                conda-forge       2MB
  + libwebp-base           1.4.0  hd590300_0                conda-forge     439kB
  + lerc                   4.0.0  h27087fc_0                conda-forge     282kB
  + libdeflate              1.17  h0b41bf4_0                conda-forge      65kB
  + llvm-openmp           18.1.5  ha31de31_0                conda-forge      59MB
  + xorg-libxau           1.0.11  hd590300_0                conda-forge      14kB
  + libhwloc              2.10.0  default_h2fb2949_1000     conda-forge       2MB
  + libgfortran5          13.2.0  hca663fb_7                conda-forge       1MB
  + pthread-stubs            0.4  h36c2ea0_1001             conda-forge       6kB
  + xorg-libxdmcp          1.1.3  h7f98852_0                conda-forge      19kB
  + freetype              2.12.1  h267a509_2                conda-forge     635kB
  + libtiff                4.5.0  h6adf6a1_2                conda-forge     407kB
  + tbb                2021.12.0  h00ab1b0_0                conda-forge     194kB
  + libgfortran-ng        13.2.0  h69a702a_7                conda-forge      24kB
  + libxcb                  1.13  h7f98852_1004             conda-forge     400kB
  + openjpeg               2.5.0  hfec8fc6_2                conda-forge     352kB
  + lcms2                   2.15  hfd0df8a_0                conda-forge     241kB
  + sleef                  3.5.1  h9b69904_2                conda-forge       2MB
  + mkl                 2022.2.1  h84fe81f_16997            conda-forge     165MB
  + libopenblas           0.3.27  pthreads_h413a1c8_0       conda-forge       6MB
  + pillow                 9.4.0  py310h023d228_1           conda-forge      46MB
  + libblas                3.9.0  22_linux64_openblas       conda-forge      15kB
  + liblapack              3.9.0  22_linux64_openblas       conda-forge      14kB
  + libcblas               3.9.0  22_linux64_openblas       conda-forge      14kB
  + magma                  2.6.2  hc72dce7_0                conda-forge     243MB
  + numpy                 1.26.4  py310hb13e2d6_0           conda-forge       7MB
  + typing_extensions     4.11.0  pyha770c72_0              conda-forge      38kB
  + cuda-version            11.8  h70ddcb2_3                conda-forge      21kB
  + nccl                2.21.5.1  h6103f9b_0                conda-forge     130MB
  + cudnn               8.9.7.29  hbc23b4c_3                conda-forge     465MB
  + pytorch               1.13.0  cuda112py310he33e0d6_200  conda-forge     358MB
  + torchvision           0.14.0  cuda112py310h7928a00_0    conda-forge       7MB

  Change:
───────────────────────────────────────────────────────────────────────────────────

  - _openmp_mutex            4.5  2_gnu                     conda-forge      24kB
  + _openmp_mutex            4.5  2_kmp_llvm                conda-forge       6kB

  Summary:

  Install: 36 packages
  Change: 1 packages

  Total download: 2GB

───────────────────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n] y
jpeg                                               240.4kB @ 556.7kB/s  0.4s
libpng                                             288.2kB @ 642.8kB/s  0.4s
libprotobuf                                          2.2MB @   4.6MB/s  0.5s
ninja                                                2.2MB @   4.3MB/s  0.5s
xorg-libxdmcp                                       19.1kB @  36.4kB/s  0.1s
_openmp_mutex                                        5.7kB @  10.1kB/s  0.1s
sleef                                                1.6MB @ 588.8kB/s  2.1s
libcblas                                            14.4kB @   5.2kB/s  0.1s
typing_extensions                                   37.6kB @  12.8kB/s  0.2s
libhwloc                                             2.4MB @ 798.6kB/s  2.6s
libwebp-base                                       439.0kB @ 129.6kB/s  0.4s
libxcb                                             399.9kB @  79.6kB/s  4.5s
pthread-stubs                                        5.6kB @ 839.0 B/s  1.7s
tbb                                                194.2kB @  21.1kB/s  2.5s
lcms2                                              240.8kB @  21.0kB/s  2.2s
libblas                                             14.5kB @   1.2kB/s  0.2s
pillow                                              46.5MB @   2.5MB/s 17.7s
numpy                                                7.0MB @ 180.1kB/s 27.3s
libdeflate                                          65.0kB @   1.7kB/s  0.3s
freetype                                           635.0kB @  15.4kB/s  2.1s
openjpeg                                           352.0kB @   8.2kB/s  1.7s
liblapack                                           14.5kB @ 332.0 B/s  0.4s
llvm-openmp                                         59.5MB @ 558.2kB/s 1m:43.2s
xorg-libxau                                         14.5kB @ 135.0 B/s  0.1s
libgfortran-ng                                      24.3kB @ 227.0 B/s  0.1s
nccl                                               130.5MB @ 649.4kB/s 2m:37.5s
lerc                                               281.8kB @   1.4kB/s  0.5s
pytorch                                            357.6MB @   1.5MB/s 3m:42.5s
torchvision                                          7.5MB @  30.6kB/s  3.9s
libopenblas                                          5.6MB @  22.5kB/s  4.0s
libtiff                                            406.7kB @   1.6kB/s  0.5s
cuda-version                                        21.0kB @  84.0 B/s  0.1s
libgfortran5                                         1.4MB @   5.7kB/s  2.0s
magma                                              242.8MB @ 851.4kB/s 2m:58.4s
cudnn                                              465.5MB @   1.4MB/s 5m:23.9s
mkl                                                164.9MB @ 501.2kB/s 2m:7.5s
cudatoolkit                                        715.6MB @   1.9MB/s 6m:7.2s

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: - By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

\ By downloading and using the cuDNN conda packages, you accept the terms and conditions of the NVIDIA cuDNN EULA -
  https://docs.nvidia.com/deeplearning/cudnn/sla/index.html

done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.27.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
  Package          Version  Build            Channel                   Size
─────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────

  + addict           2.4.0  pyhd8ed1ab_2     conda-forge/noarch         8kB
  + joblib           1.4.2  pyhd8ed1ab_0     conda-forge/noarch       220kB
  + pandas           2.2.2  py310hcc13569_0  conda-forge/linux-64      13MB
  + plyfile          1.0.3  pyhd8ed1ab_0     conda-forge/noarch        28kB
  + python-tzdata   2024.1  pyhd8ed1ab_0     conda-forge/noarch       144kB
  + pytz            2024.1  pyhd8ed1ab_0     conda-forge/noarch       189kB
  + scikit-learn     1.4.2  py310h1fdf081_0  conda-forge/linux-64       9MB
  + threadpoolctl    3.5.0  pyhc1e730c_0     conda-forge/noarch        24kB

  Summary:

  Install: 8 packages

  Total download: 23MB

─────────────────────────────────────────────────────────────────────────────

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.27.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Encountered problems while solving:
  - package open3d-0.14.1-py39_0 requires python >=3.9,<3.10.0a0, but none of the providers can be installed

Collecting einops
  Using cached einops-0.8.0-py3-none-any.whl.metadata (12 kB)
Using cached einops-0.8.0-py3-none-any.whl (43 kB)
Installing collected packages: einops
Successfully installed einops-0.8.0
Collecting hydra-core==1.1.1
  Using cached hydra_core-1.1.1-py3-none-any.whl.metadata (4.1 kB)
Collecting omegaconf==2.1.* (from hydra-core==1.1.1)
  Using cached omegaconf-2.1.2-py3-none-any.whl.metadata (3.6 kB)
Collecting antlr4-python3-runtime==4.8 (from hydra-core==1.1.1)
  Using cached antlr4_python3_runtime-4.8-py3-none-any.whl
Requirement already satisfied: PyYAML>=5.1.0 in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from omegaconf==2.1.*->hydra-core==1.1.1) (6.0.1)
Using cached hydra_core-1.1.1-py3-none-any.whl (145 kB)
Using cached omegaconf-2.1.2-py3-none-any.whl (74 kB)
Installing collected packages: antlr4-python3-runtime, omegaconf, hydra-core
Successfully installed antlr4-python3-runtime-4.8 hydra-core-1.1.1 omegaconf-2.1.2
Collecting wandb
  Using cached wandb-0.17.0-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting click!=8.0.0,>=7.1 (from wandb)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting docker-pycreds>=0.4.0 (from wandb)
  Using cached docker_pycreds-0.4.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting gitpython!=3.1.29,>=1.0.0 (from wandb)
  Using cached GitPython-3.1.43-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: platformdirs in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from wandb) (4.2.1)
Collecting protobuf!=4.21.0,<5,>=3.19.0 (from wandb)
  Using cached protobuf-4.25.3-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Collecting psutil>=5.0.0 (from wandb)
  Using cached psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
Requirement already satisfied: pyyaml in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from wandb) (6.0.1)
Requirement already satisfied: requests<3,>=2.0.0 in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from wandb) (2.31.0)
Collecting sentry-sdk>=1.0.0 (from wandb)
  Using cached sentry_sdk-2.1.1-py2.py3-none-any.whl.metadata (10 kB)
Collecting setproctitle (from wandb)
  Using cached setproctitle-1.3.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.9 kB)
Requirement already satisfied: setuptools in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from wandb) (69.5.1)
Requirement already satisfied: six>=1.4.0 in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from docker-pycreds>=0.4.0->wandb) (1.16.0)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.29,>=1.0.0->wandb)
  Using cached gitdb-4.0.11-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb) (2024.2.2)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb)
  Using cached smmap-5.0.1-py3-none-any.whl.metadata (4.3 kB)
Using cached wandb-0.17.0-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.7 MB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
Using cached GitPython-3.1.43-py3-none-any.whl (207 kB)
Using cached protobuf-4.25.3-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
Using cached psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (288 kB)
Using cached sentry_sdk-2.1.1-py2.py3-none-any.whl (277 kB)
Using cached setproctitle-1.3.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30 kB)
Using cached gitdb-4.0.11-py3-none-any.whl (62 kB)
Using cached smmap-5.0.1-py3-none-any.whl (24 kB)
Installing collected packages: smmap, setproctitle, sentry-sdk, psutil, protobuf, docker-pycreds, click, gitdb, gitpython, wandb
Successfully installed click-8.1.7 docker-pycreds-0.4.0 gitdb-4.0.11 gitpython-3.1.43 protobuf-4.25.3 psutil-5.9.8 sentry-sdk-2.1.1 setproctitle-1.3.3 smmap-5.0.1 wandb-0.17.0
Collecting termcolor
  Using cached termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
Using cached termcolor-2.4.0-py3-none-any.whl (7.7 kB)
Installing collected packages: termcolor
Successfully installed termcolor-2.4.0
Collecting ipython
  Using cached ipython-8.24.0-py3-none-any.whl.metadata (4.9 kB)
Collecting decorator (from ipython)
  Using cached decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
Collecting jedi>=0.16 (from ipython)
  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting matplotlib-inline (from ipython)
  Using cached matplotlib_inline-0.1.7-py3-none-any.whl.metadata (3.9 kB)
Collecting prompt-toolkit<3.1.0,>=3.0.41 (from ipython)
  Using cached prompt_toolkit-3.0.43-py3-none-any.whl.metadata (6.5 kB)
Collecting pygments>=2.4.0 (from ipython)
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting stack-data (from ipython)
  Using cached stack_data-0.6.3-py3-none-any.whl.metadata (18 kB)
Collecting traitlets>=5.13.0 (from ipython)
  Using cached traitlets-5.14.3-py3-none-any.whl.metadata (10 kB)
Collecting exceptiongroup (from ipython)
  Using cached exceptiongroup-1.2.1-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: typing-extensions>=4.6 in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from ipython) (4.11.0)
Collecting pexpect>4.3 (from ipython)
  Using cached pexpect-4.9.0-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting parso<0.9.0,>=0.8.3 (from jedi>=0.16->ipython)
  Using cached parso-0.8.4-py2.py3-none-any.whl.metadata (7.7 kB)
Collecting ptyprocess>=0.5 (from pexpect>4.3->ipython)
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting wcwidth (from prompt-toolkit<3.1.0,>=3.0.41->ipython)
  Using cached wcwidth-0.2.13-py2.py3-none-any.whl.metadata (14 kB)
Collecting executing>=1.2.0 (from stack-data->ipython)
  Using cached executing-2.0.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting asttokens>=2.1.0 (from stack-data->ipython)
  Using cached asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting pure-eval (from stack-data->ipython)
  Using cached pure_eval-0.2.2-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: six>=1.12.0 in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from asttokens>=2.1.0->stack-data->ipython) (1.16.0)
Using cached ipython-8.24.0-py3-none-any.whl (816 kB)
Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
Using cached pexpect-4.9.0-py2.py3-none-any.whl (63 kB)
Using cached prompt_toolkit-3.0.43-py3-none-any.whl (386 kB)
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached traitlets-5.14.3-py3-none-any.whl (85 kB)
Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Using cached exceptiongroup-1.2.1-py3-none-any.whl (16 kB)
Using cached matplotlib_inline-0.1.7-py3-none-any.whl (9.9 kB)
Using cached stack_data-0.6.3-py3-none-any.whl (24 kB)
Using cached asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
Using cached executing-2.0.1-py2.py3-none-any.whl (24 kB)
Using cached parso-0.8.4-py2.py3-none-any.whl (103 kB)
Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Using cached wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
Installing collected packages: wcwidth, pure-eval, ptyprocess, traitlets, pygments, prompt-toolkit, pexpect, parso, executing, exceptiongroup, decorator, asttokens, stack-data, matplotlib-inline, jedi, ipython
Successfully installed asttokens-2.4.1 decorator-5.1.1 exceptiongroup-1.2.1 executing-2.0.1 ipython-8.24.0 jedi-0.19.1 matplotlib-inline-0.1.7 parso-0.8.4 pexpect-4.9.0 prompt-toolkit-3.0.43 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.18.0 stack-data-0.6.3 traitlets-5.14.3 wcwidth-0.2.13
Collecting torchsde
  Using cached torchsde-0.2.6-py3-none-any.whl.metadata (5.3 kB)
Collecting torchdiffeq
  Using cached torchdiffeq-0.2.3-py3-none-any.whl.metadata (488 bytes)
Requirement already satisfied: numpy>=1.19 in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from torchsde) (1.26.4)
Requirement already satisfied: scipy>=1.5 in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from torchsde) (1.13.0)
Requirement already satisfied: torch>=1.6.0 in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from torchsde) (1.11.0)
Collecting trampoline>=0.1.2 (from torchsde)
  Using cached trampoline-0.1.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: typing-extensions in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from torch>=1.6.0->torchsde) (4.11.0)
Using cached torchsde-0.2.6-py3-none-any.whl (61 kB)
Using cached torchdiffeq-0.2.3-py3-none-any.whl (31 kB)
Using cached trampoline-0.1.2-py3-none-any.whl (5.2 kB)
Installing collected packages: trampoline, torchsde, torchdiffeq
Successfully installed torchdiffeq-0.2.3 torchsde-0.2.6 trampoline-0.1.2

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.27.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

  Package    Version  Build         Channel                 Size
──────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────

  + imageio   2.34.1  pyh4b66e23_0  conda-forge/noarch     291kB

  Summary:

  Install: 1 packages

  Total download: 291kB

──────────────────────────────────────────────────────────────────

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting mujoco==2.3.2
  Using cached mujoco-2.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (35 kB)
Collecting absl-py (from mujoco==2.3.2)
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting glfw (from mujoco==2.3.2)
  Using cached glfw-2.7.0-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38-none-manylinux2014_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: numpy in /home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages (from mujoco==2.3.2) (1.26.4)
Collecting pyopengl (from mujoco==2.3.2)
  Using cached PyOpenGL-3.1.7-py3-none-any.whl.metadata (3.2 kB)
Using cached mujoco-2.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.2 MB)
Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
Using cached glfw-2.7.0-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38-none-manylinux2014_x86_64.whl (211 kB)
Using cached PyOpenGL-3.1.7-py3-none-any.whl (2.4 MB)
Installing collected packages: pyopengl, glfw, absl-py, mujoco
Successfully installed absl-py-2.1.0 glfw-2.7.0 mujoco-2.3.2 pyopengl-3.1.7

Installing D3il-Sim Package
Obtaining file:///dprl/d3il/environments/d3il
  Preparing metadata (setup.py) ... done
Installing collected packages: environments.d3il.d3il_sim
  Running setup.py develop for environments.d3il.d3il_sim
Successfully installed environments.d3il.d3il_sim-0.2
(base) silencht@silencht:~/d3il$ conda activate d3il2
(d3il2) silencht@silencht:~/d3il$ conda list
# packages in environment at /home/silencht/anaconda3/envs/d3il2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
absl-py                   2.1.0                    pypi_0    pypi
addict                    2.4.0              pyhd8ed1ab_2    conda-forge
alsa-lib                  1.2.3.2              h166bdaf_0    conda-forge
antlr4-python3-runtime    4.8                      pypi_0    pypi
archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
assimp                    5.2.4                h4c92fa2_0    conda-forge
asttokens                 2.4.1                    pypi_0    pypi
boltons                   24.0.0             pyhd8ed1ab_0    conda-forge
boost                     1.74.0          py310h7c3ba0c_5    conda-forge
boost-cpp                 1.74.0               h312852a_4    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0           py310hc6cd4ac_1    conda-forge
bullet-cpp                3.25                 hcc13569_2    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.28.1               hd590300_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py310h2fee648_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     22.9.0          py310hff52083_2    conda-forge
conda-libmamba-solver     22.8.1             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
console_bridge            1.0.2                h924138e_1    conda-forge
contourpy                 1.2.1           py310hd41b1e2_0    conda-forge
cryptography              39.0.0          py310h65dfdc0_0    conda-forge
cuda-version              11.8                 h70ddcb2_3    conda-forge
cudatoolkit               11.8.0              h4ba93d1_13    conda-forge
cudnn                     8.9.7.29             hbc23b4c_3    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
decorator                 5.1.1                    pypi_0    pypi
distro                    1.9.0              pyhd8ed1ab_0    conda-forge
docker-pycreds            0.4.0                    pypi_0    pypi
eigen                     3.4.0                h00ab1b0_0    conda-forge
eigenpy                   2.7.13          py310hf3e5c9c_0    conda-forge
einops                    0.8.0                    pypi_0    pypi
environments-d3il-d3il-sim 0.2                       dev_0    <develop>
exceptiongroup            1.2.1                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
expat                     2.6.2                h59595ed_0    conda-forge
ffmpeg                    4.3.2                h37c90e5_3    conda-forge
fmt                       10.2.1               h00ab1b0_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonttools                 4.51.0          py310h2372a71_0    conda-forge
freeglut                  3.2.2                hac7e632_2    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gettext                   0.22.5               h59595ed_2    conda-forge
gettext-tools             0.22.5               h59595ed_2    conda-forge
gin-config                0.5.0              pyhd8ed1ab_0    conda-forge
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
glfw                      2.7.0                    pypi_0    pypi
gmp                       6.3.0                h59595ed_1    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
gst-plugins-base          1.18.5               hf529b03_2    conda-forge
gstreamer                 1.18.5               h9f60fe5_3    conda-forge
gym                       0.21.0          py310hfdc917e_2    conda-forge
harfbuzz                  3.1.1                h83ec7ef_0    conda-forge
hdf5                      1.12.1          nompi_h2386368_104    conda-forge
hpp-fcl                   2.1.2           py310h2ff80d2_1    conda-forge
hydra-core                1.1.1                    pypi_0    pypi
icu                       68.2                 h9c3ff4c_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
imageio                   2.34.1             pyh4b66e23_0    conda-forge
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
ipython                   8.24.0                   pypi_0    pypi
jasper                    2.0.33               h0ff4b12_1    conda-forge
jedi                      0.19.1                   pypi_0    pypi
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               2.4             py310hff52083_3    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py310hd41b1e2_1    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.40                 h55db66e_0    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libarchive                3.5.2                hccf745f_1    conda-forge
libasprintf               0.22.5               h661eb56_2    conda-forge
libasprintf-devel         0.22.5               h661eb56_2    conda-forge
libblas                   3.9.0            16_linux64_mkl    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0            16_linux64_mkl    conda-forge
libclang                  11.1.0          default_ha53f305_1    conda-forge
libcurl                   7.86.0               h7bff187_1    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h77fa898_7    conda-forge
libgettextpo              0.22.5               h59595ed_2    conda-forge
libgettextpo-devel        0.22.5               h59595ed_2    conda-forge
libgfortran-ng            13.2.0               h69a702a_7    conda-forge
libgfortran5              13.2.0               hca663fb_7    conda-forge
libglib                   2.80.1               hf974151_0    conda-forge
libglu                    9.0.0             hac7e632_1003    conda-forge
libgomp                   13.2.0               h77fa898_7    conda-forge
libhwloc                  2.7.1                h32351e8_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0            16_linux64_mkl    conda-forge
liblapacke                3.9.0            16_linux64_mkl    conda-forge
libllvm11                 11.1.0               he0ac6c6_5    conda-forge
libmamba                  0.27.0               h0dd8ff0_0    conda-forge
libmambapy                0.27.0          py310hab0e683_0    conda-forge
libnghttp2                1.51.0               hdcd2b5c_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.27          pthreads_h413a1c8_0    conda-forge
libopencv                 4.5.5            py31he7a5e20_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libpq                     13.8                 hd77ab85_0    conda-forge
libprotobuf               3.19.6               h3eb15da_0    conda-forge
libsolv                   0.7.29               ha6fb4c9_0    conda-forge
libsqlite                 3.45.3               h2797004_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              13.2.0               hc0a3c3a_7    conda-forge
libtiff                   4.3.0                h0fcbabc_4    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-openmp               18.1.5               ha31de31_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
magma                     2.6.2                hc72dce7_0    conda-forge
mamba                     0.27.0          py310hf87f941_0    conda-forge
matplotlib                3.8.4           py310hff52083_0    conda-forge
matplotlib-base           3.8.4           py310h62c0568_0    conda-forge
matplotlib-inline         0.1.7                    pypi_0    pypi
menuinst                  2.0.2           py310hff52083_0    conda-forge
mkl                       2022.2.1         h84fe81f_16997    conda-forge
mujoco                    2.3.2                    pypi_0    pypi
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.32               h14678bc_0    conda-forge
mysql-libs                8.0.32               h54cf53e_0    conda-forge
nccl                      2.21.5.1             h6103f9b_0    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
ninja                     1.12.0               h00ab1b0_0    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.100                hca3bf56_0    conda-forge
numpy                     1.26.4          py310hb13e2d6_0    conda-forge
octomap                   1.9.8                h924138e_0    conda-forge
olefile                   0.47               pyhd8ed1ab_0    conda-forge
omegaconf                 2.1.2                    pypi_0    pypi
opencv                    4.5.5            py31hff52083_0    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.5.0                h7d73246_0    conda-forge
openssl                   1.1.1w               hd590300_0    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py310hcc13569_0    conda-forge
parso                     0.8.4                    pypi_0    pypi
pcre2                     10.43                hcad00b1_0    conda-forge
pexpect                   4.9.0                    pypi_0    pypi
pillow                    8.4.0           py310h07f4688_0    conda-forge
pinocchio                 2.6.9           py310hf3e5c9c_1    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
platformdirs              4.2.1              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
plyfile                   1.0.3              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.43                   pypi_0    pypi
protobuf                  4.25.3                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py-opencv                 4.5.5            py31hfdc917e_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pybullet                  3.25            py310hcc13569_2    conda-forge
pycosat                   0.6.6           py310h2372a71_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pygments                  2.18.0                   pypi_0    pypi
pyopengl                  3.1.7                    pypi_0    pypi
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3          py310hff52083_8    conda-forge
pyqt-impl                 5.12.3          py310h1f8e252_8    conda-forge
pyqt5-sip                 4.19.18         py310h122e73d_8    conda-forge
pyqtchart                 5.12            py310hfcd6d55_8    conda-forge
pyqtwebengine             5.12.1          py310hfcd6d55_8    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.8          h257c98d_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pytorch                   1.11.0          cpu_py310h2272b30_0    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py310h2372a71_1    conda-forge
qhull                     2020.2               h4bd325d_2    conda-forge
qt                        5.12.9               hda022c4_4    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reproc                    14.2.4.post0         hd590300_1    conda-forge
reproc-cpp                14.2.4.post0         h59595ed_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.18.6          py310h2372a71_0    conda-forge
ruamel.yaml.clib          0.2.8           py310h2372a71_0    conda-forge
ruamel_yaml               0.15.80         py310h2372a71_1009    conda-forge
scikit-learn              1.4.2           py310h1fdf081_0    conda-forge
scipy                     1.13.0          py310h93e2701_1    conda-forge
sentry-sdk                2.1.1                    pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                69.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.5.1                h9b69904_2    conda-forge
smmap                     5.0.1                    pypi_0    pypi
sqlite                    3.45.3               h2c6b66d_0    conda-forge
stack-data                0.6.3                    pypi_0    pypi
tbb                       2021.7.0             h924138e_0    conda-forge
termcolor                 2.4.0                    pypi_0    pypi
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tinyxml                   2.6.2                h4bd325d_2    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
torchdiffeq               0.2.3                    pypi_0    pypi
torchsde                  0.2.6                    pypi_0    pypi
torchvision               0.12.0          cpu_py310h3f5528d_0    conda-forge
tornado                   6.4             py310h2372a71_0    conda-forge
tqdm                      4.66.4             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3                   pypi_0    pypi
trampoline                0.1.2                    pypi_0    pypi
truststore                0.8.0              pyhd8ed1ab_0    conda-forge
typing_extensions         4.11.0             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
unicodedata2              15.1.0          py310h2372a71_0    conda-forge
urdfdom                   3.1.1                h8a9b4ce_0    conda-forge
urdfdom_headers           1.1.1                h00ab1b0_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
wandb                     0.17.0                   pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
x264                      1!161.3030           h7f98852_1    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.7.0                h59595ed_3    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstandard                 0.19.0          py310h5764c6d_0    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
(d3il2) silencht@silencht:~/d3il$ bash scripts/sorting_4_vision/ddpm_encdec_benchmark.sh 
/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'sorting_4_vision_config': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
[2024-05-09 18:11:34,602][HYDRA] Launching 1 jobs locally
[2024-05-09 18:11:34,602][HYDRA] 	#0 : seed=0 agents=ddpm_encdec_vision_agent agent_name=ddpm_encdec_vision window_size=8 group=ddpm_encdec_vision_seeds
ROBOMIMIC WARNING(
    No private macro file found!
    It is recommended to use a private macro file
    To setup, run: python /dprl/d3il/agents/models/robomimic/scripts/setup_macros.py
)
Error executing job with overrides: ['seed=0', 'agents=ddpm_encdec_vision_agent', 'agent_name=ddpm_encdec_vision', 'window_size=8', 'group=ddpm_encdec_vision_seeds']
An error occurred during Hydra's exception formatting:
TypeError("print_exception() got an unexpected keyword argument 'etype'")
Traceback (most recent call last):
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 283, in run_and_report
    print_exception(etype=None, value=ex, tb=final_tb)  # type: ignore
TypeError: print_exception() got an unexpected keyword argument 'etype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dprl/d3il/run_vision.py", line 89, in <module>
    main()
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 385, in _run_hydra
    run_and_report(
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 294, in run_and_report
    raise ex
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 386, in <lambda>
    lambda: hydra.multirun(
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 140, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 161, in sweep
    _ = r.return_value
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/dprl/d3il/run_vision.py", line 54, in main
    agent = hydra.utils.instantiate(cfg.agents)
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "/dprl/d3il/agents/ddpm_encdec_vision_agent.py", line 125, in __init__
    super().__init__(model, trainset=trainset, valset=valset, train_batch_size=train_batch_size,
  File "/dprl/d3il/agents/base_agent.py", line 33, in __init__
    self.model = hydra.utils.instantiate(model).to(device)
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "/dprl/d3il/agents/ddpm_encdec_vision_agent.py", line 29, in __init__
    self.obs_encoder = hydra.utils.instantiate(obs_encoder).to(device)
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/silencht/anaconda3/envs/d3il2/lib/python3.10/site-packages/torch/cuda/__init__.py", line 210, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Error instantiating 'agents.ddpm_encdec_vision_agent.DiffusionAgent' : Error instantiating 'agents.ddpm_encdec_vision_agent.DiffusionPolicy' : Torch not compiled with CUDA enabled
```

**Comment by silencht** [comment]
I solved the above problem by replacing mamba with conda.  However, the following problem occurred during training:
```bash
(d3il2) silencht@silencht:~/d3il$ bash scripts/sorting_4_vision/ddpm_encdec_benchmark.sh 
/home/silencht/anaconda3/envs/d3il/lib/python3.9/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'sorting_4_vision_config': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
[2024-05-10 09:40:56,440][HYDRA] Launching 1 jobs locally
[2024-05-10 09:40:56,440][HYDRA] 	#0 : seed=0 agents=ddpm_encdec_vision_agent agent_name=ddpm_encdec_vision window_size=8 group=ddpm_encdec_vision_seeds
ROBOMIMIC WARNING(
    No private macro file found!
    It is recommended to use a private macro file
    To setup, run: python /dprl/d3il/agents/models/robomimic/scripts/setup_macros.py
)
/home/silencht/anaconda3/envs/d3il/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/silencht/anaconda3/envs/d3il/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
[2024-05-10 09:41:06,034][agents.models.diffusion.diffusion_models][INFO] - number of parameters: 3.748500e+05
[2024-05-10 09:41:08,968][root][INFO] - Loading Sorting Dataset
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:13<00:00,  7.15it/s]
[2024-05-10 09:41:23,006][root][INFO] - Loading Sorting Dataset
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:14<00:00,  6.76it/s]
[2024-05-10 09:41:37,937][agents.utils.scaler][INFO] - Datset Info: state min: [-2.87769967 -2.62087375] and max: [2.45655452 1.81934526], action min: [-1.65338498 -1.49557176] and max: [1.68398661 1.03862885]
[2024-05-10 09:41:37,937][agents.utils.scaler][INFO] - Training dataset size: input (33685, 2) target (33685, 2)
[2024-05-10 09:41:37,938][agents.base_agent][INFO] - The model has a total amount of 22769026 parameters
[2024-05-10 09:41:44,996][OpenGL.acceleratesupport][INFO] - No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
pybullet build time: Oct 14 2023 15:48:24
[2024-05-10 09:41:50,471][environments.d3il.d3il_sim.sims.sl][INFO] - No module named 'py_at_broker'
[2024-05-10 09:41:50,471][environments.d3il.d3il_sim.sims.sl][INFO] - No SL installed. SL simulation and control is not available.
 25%|██████████████████████████████▊                                                                                            | 1/4 [01:17<03:53, 77.82s/it][2024-05-10 09:44:16,325][simulation.sorting_sim][INFO] - Starting trained model evaluation
there are cpus:  16
196669 {0}
/home/silencht/anaconda3/envs/d3il/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
Final IK error (74 iterations):  7.2438426746618415e-06
Final IK error (0 iterations):  7.2438426746618415e-06
Context 0 Rollout 0
p(m|c) tensor([[0., 0., 0., 0., 0., 0.]])
Successrate 0.0
entropy nan
KL nan
[2024-05-10 09:44:56,434][__main__][INFO] - New best success rate. Stored weights have been updated!
 50%|█████████████████████████████████████████████████████████████▌                                                             | 2/4 [03:05<03:11, 95.63s/it]/home/silencht/anaconda3/envs/d3il/lib/python3.9/site-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
 75%|████████████████████████████████████████████████████████████████████████████████████████████▎                              | 3/4 [04:17<01:24, 84.47s/it][2024-05-10 09:47:19,052][simulation.sorting_sim][INFO] - Starting trained model evaluation
there are cpus:  16
196669 {0}
Final IK error (74 iterations):  7.2438426746618415e-06
Final IK error (0 iterations):  7.2438426746618415e-06
Context 0 Rollout 0
p(m|c) tensor([[0., 0., 0., 0., 0., 0.]])
Successrate 0.0
entropy nan
KL nan
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [06:00<00:00, 90.16s/it]
[2024-05-10 09:47:51,342][__main__][INFO] - Training done!
[2024-05-10 09:47:51,431][agents.ddpm_encdec_vision_agent][INFO] - Loaded pre-trained model parameters
[2024-05-10 09:47:51,445][simulation.sorting_sim][INFO] - Starting trained model evaluation
there are cpus:  16
Start 0
pybullet build time: Oct 14 2023 15:48:24
ROBOMIMIC WARNING(
    No private macro file found!
    It is recommended to use a private macro file
    To setup, run: python /dprl/d3il/agents/models/robomimic/scripts/setup_macros.py
)
Start 1
197409 {0}
/home/silencht/anaconda3/envs/d3il/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
Final IK error (74 iterations):  7.2438426746618415e-06
Final IK error (0 iterations):  7.2438426746618415e-06
Context 0 Rollout 0
pybullet build time: Oct 14 2023 15:48:24
ROBOMIMIC WARNING(
    No private macro file found!
    It is recommended to use a private macro file
    To setup, run: python /dprl/d3il/agents/models/robomimic/scripts/setup_macros.py
)
Start 2
197519 {1}
/home/silencht/anaconda3/envs/d3il/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
Final IK error (74 iterations):  7.2438426746618415e-06
Final IK error (0 iterations):  7.2438426746618415e-06
Context 12 Rollout 0
pybullet build time: Oct 14 2023 15:48:24
ROBOMIMIC WARNING(
    No private macro file found!
    It is recommended to use a private macro file
    To setup, run: python /dprl/d3il/agents/models/robomimic/scripts/setup_macros.py
)
Start 3
197550 {2}
/home/silencht/anaconda3/envs/d3il/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
Final IK error (74 iterations):  7.2438426746618415e-06
Final IK error (0 iterations):  7.2438426746618415e-06
Context 24 Rollout 0
Context 24 Rollout 1
Context 0 Rollout 1
Context 12 Rollout 1
pybullet build time: Oct 14 2023 15:48:24
ROBOMIMIC WARNING(
    No private macro file found!
    It is recommended to use a private macro file
    To setup, run: python /dprl/d3il/agents/models/robomimic/scripts/setup_macros.py
)
Start 4
197581 {3}
/home/silencht/anaconda3/envs/d3il/lib/python3.9/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
Context 0 Rollout 2
Final IK error (74 iterations):  7.2438426746618415e-06
Final IK error (0 iterations):  7.2438426746618415e-06
Context 36 Rollout 0
Context 24 Rollout 2
Context 12 Rollout 2
Context 24 Rollout 3
Context 0 Rollout 3
Context 36 Rollout 1
Context 12 Rollout 3
Context 0 Rollout 4
Context 24 Rollout 4
Context 36 Rollout 2
Context 12 Rollout 4
pybullet build time: Oct 14 2023 15:48:24
Context 24 Rollout 5
Context 0 Rollout 5
Context 36 Rollout 3
Context 12 Rollout 5
ROBOMIMIC WARNING(
    No private macro file found!
    It is recommended to use a private macro file
    To setup, run: python /dprl/d3il/agents/models/robomimic/scripts/setup_macros.py
)
^CProcess SpawnProcess-9:
```
So, what happened? How can I solve it? Looking forward to your reply asap.
